### ISSUE TITLE
New generator

### ISSUE THREAD

**Issue by nilshelmig** [miniBill/elm-bare-generator#1]
Hello :wave: 

I wrote a new generator inspired by this project. At first I wanted to create a merge request, but I planned major changes, so I wrote my own from scratch (I ended up writing the schema parser pretty much the same way as you though). You can find the project [here](https://github.com/nilshelmig/elm-bare-generator)

Reason for a new generator:
- many `Debug.todo` calls which blocks providing optimized JavaScript code
- generated code exposed the codecs. For better user experience the module should provide functions to create messages and values from messages
- missing error handling in CLI
  - No errors for wrong schema
  - No errors for wrong usages of BARE types, e.g. `void` used as map key
- not available as npm CLI package

I mentioned you explicitly in the README of the new generator, because of your effort :smiley:

I would like to see my generator implementation as the preferred one for elm-bare, but I'm also fine if you want to enhance your own implementation. I can take the npm package down :slightly_smiling_face: 

Best wishes!

**Comment by miniBill** [comment]
LGTM, this project was basically a "hey, I should create a generator cause people might need it" but I will archive it and point people to yours, which is way more complete and polished
